Repository YohanGH/WisperHub, pull requests merged in 2024-05, with the labels that each got.

#1 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, review requested

#15 Lith3 5 messagecomposer
  wisperhub/src/App.jsx
  wisperhub/src/components/MessageComposer/InputMessage/InputMessage.jsx
  wisperhub/src/components/MessageComposer/MessageComposer.jsx
Labels: review requested

#16 Create two files message jsx and css module in to folder message
  wisperhub/src/components/message/Message.jsx
  wisperhub/src/components/message/message-style.module.css
Labels: review

#17 Fix conv bug
  wisperhub/src/App.jsx
  wisperhub/src/components/conversation/conversation.jsx
  wisperhub/src/components/message_composer/MessageComposer.jsx
  wisperhub/src/components/message_composer/input_message/InputMessage.jsx
Labels: review requested

#24 Socket
  wisperhub/.babelrc
  wisperhub/.swcrc
  wisperhub/app.js
  wisperhub/index.html
  wisperhub/package.json
  wisperhub/postcss.config.js
  wisperhub/src/App.js
  wisperhub/src/components/conversation/conversation-style.css
  wisperhub/src/components/conversation/conversation-style.module.css
  wisperhub/src/components/conversation/conversation.js
  wisperhub/src/components/message_composer/MessageComposer.js
  wisperhub/src/components/message_composer/input_message/InputMessage.js
  wisperhub/src/index.js
  wisperhub/webpack.config.js
Labels: corrections done, review requested

#25 Yohan gh fix socket
  wisperhub/index.html
  wisperhub/src/index.js
Labels: bug, review requested

#23 Import frame motion create loading page and progessBar
  wisperhub/package.json
  wisperhub/src/App.js
  wisperhub/src/components/MainApp.js
  wisperhub/src/components/loading_page/LoadingPage.js
  wisperhub/src/components/loading_page/loading-page-styles.css
  wisperhub/src/components/message/Message.jsx
  wisperhub/src/components/message/message-style.module.css
  wisperhub/src/components/progress_bar/ProgressBar.js
  wisperhub/src/components/progress_bar/progress-bar-style.css
  wisperhub/webpack.config.js
Labels: corrections done, review requested

#27 Lith3 fix message
  wisperhub/src/components/MainApp.js
  wisperhub/src/components/conversation/conversation.js
  wisperhub/src/components/message/Message.js
  wisperhub/src/components/message_composer/input_message/InputMessage.js
Labels: changes requested, review requested

#28 Create folder dates and component Dates for message watch hours and Date
  wisperhub/src/components/dates/Dates.js
  wisperhub/src/components/message/Message.js
Labels: review requested

#29 7-emoji
  wisperhub/src/components/emoji/Emoji-style.css
  wisperhub/src/components/emoji/Emoji.js
  wisperhub/src/components/message_composer/input_message/InputMessage.js
Labels: corrections done, review requested

#30 Fix emoji
  wisperhub/package.json
  wisperhub/src/components/emoji/Emoji-style.css
  wisperhub/src/components/emoji/Emoji.js
  wisperhub/src/components/message_composer/input_message/InputMessage.js
Labels: review requested

#31 Develop
  wisperhub/.babelrc
  wisperhub/.swcrc
  wisperhub/app.js
  wisperhub/index.html
  wisperhub/package.json
  wisperhub/postcss.config.js
  wisperhub/src/App.js
  wisperhub/src/App.jsx
  wisperhub/src/components/MainApp.js
  wisperhub/src/components/conversation/conversation-style.css
  wisperhub/src/components/conversation/conversation.js
  wisperhub/src/components/dates/Dates.js
  wisperhub/src/components/emoji/Emoji-style.css
  wisperhub/src/components/emoji/Emoji.js
  wisperhub/src/components/loading_page/LoadingPage.js
  wisperhub/src/components/loading_page/loading-page-styles.css
  wisperhub/src/components/message/Message.js
  wisperhub/src/components/message_composer/MessageComposer.js
  wisperhub/src/components/message_composer/input_message/InputMessage.js
  wisperhub/src/components/progress_bar/ProgressBar.js
  wisperhub/src/components/progress_bar/progress-bar-style.css
  wisperhub/src/index.js
  wisperhub/webpack.config.js
Labels: review requested

#32 fix server express crash
  wisperhub/app.js
  wisperhub/index.html
Labels: review requested

#35 Fix conflic
  wisperhub/index.html
Labels: review requested

#37 Fix merge confl
  wisperhub/app.js
  wisperhub/index.html
Labels: review requested

#36 Fix merge confl
  wisperhub/index.html
Labels: review requested

#38 Serv branch
  .gitignore
  README.md
  wisperhub/.eslintrc.cjs
  wisperhub/.gitignore
  wisperhub/.swcrc
  wisperhub/app.js
  wisperhub/index.html
Labels: review requested

#40 Merge conflict
  wisperhub/.swcrc
  wisperhub/app.js
Labels: review requested

#43 Modification description keywords and title, updates readme
  README.md
  wisperhub/public/vite.svg
  wisperhub/src/assets/images/favicon.png
Labels: review requested

#44 Fix input bar css
  wisperhub/src/App.css
  wisperhub/src/components/MainApp.js
  wisperhub/src/components/conversation/conversation-style.css
  wisperhub/src/components/emoji/Emoji-style.css
  wisperhub/src/components/message_composer/MessageComposer.js
  wisperhub/src/components/message_composer/input_message/InputMessage.js
  wisperhub/src/components/message_composer/messageComposer-style.css
Labels: review requested

#47 Yohan gh 20 registrationform
  wisperhub/package.json
  wisperhub/src/components/registration_form/RegistrationForm.js
  wisperhub/src/components/registration_form/registration-form-style.css
Labels: corrections done, review requested

#48 Fix css
  wisperhub/src/components/emoji/Emoji-style.css
  wisperhub/src/components/message_composer/messageComposer-style.css
Labels: review requested

#49 Lith3 socket.io
  wisperhub/package.json
  wisperhub/src/App.js
  wisperhub/src/components/MainApp.js
  wisperhub/src/components/emoji/Emoji.js
  wisperhub/src/components/message_composer/MessageComposer.js
  wisperhub/src/components/message_composer/input_message/InputMessage.js
  wisperhub/src/main.jsx
Labels: review requested

#50 Fix app.js
  wisperhub/app.js
Labels: review requested

#54 Lith3 username
  wisperhub/src/components/MainApp.js
  wisperhub/src/components/logging/Logging.js
  wisperhub/src/components/logging/logging-style.css
  wisperhub/src/components/message_composer/MessageComposer.js
  wisperhub/src/components/message_composer/input_message/InputMessage.js
Labels: review requested

#55 Fix prop type
  wisperhub/src/components/logging/Logging.js
  wisperhub/src/components/logging/logging-style.css
Labels: review requested

#56 Fix css logging
  wisperhub/package.json
  wisperhub/src/App.css
  wisperhub/src/assets/images/logo.png
  wisperhub/src/assets/images/send.png
  wisperhub/src/components/conversation/conversation-style.css
  wisperhub/src/components/conversation/conversation.js
  wisperhub/src/components/emoji/Emoji-style.css
  wisperhub/src/components/emoji/Emoji.js
  wisperhub/src/components/logging/Logging.js
  wisperhub/src/components/logging/logging-style.css
  wisperhub/src/components/message/Message.js
  wisperhub/src/components/message_composer/input_message/InputMessage.js
  wisperhub/src/components/message_composer/messageComposer-style.css
  wisperhub/webpack.config.js
Labels: review requested

#58 Fix cgu-style
  wisperhub/src/components/MainApp.js
  wisperhub/src/components/cgu/CGU.js
  wisperhub/src/components/cgu/cgu-style.css
Labels: review requested

#62 Fix ux css
  wisperhub/src/components/MainApp.js
  wisperhub/src/components/cgu/cgu-style.css
  wisperhub/src/components/emoji/Emoji-style.css
  wisperhub/src/components/loading_page/loading-page-styles.css
  wisperhub/src/components/logging/Logging.js
  wisperhub/src/components/logging/logging-style.css
Labels: review requested

#63 Yohan gh version 1 0 0
  wisperhub/package.json
  wisperhub/src/components/message_composer/input_message/InputMessage.js
  wisperhub/webpack.config.js
Labels: review requested

#67 Merge confl
  README.md
  wisperhub/README.md
  wisperhub/index.html
  wisperhub/src/App.js
  wisperhub/src/components/dates/Dates.js
  wisperhub/src/components/emoji/Emoji-style.css
  wisperhub/src/components/emoji/Emoji.js
  wisperhub/src/components/message/Message.js
  wisperhub/src/components/message_composer/input_message/InputMessage.js
Labels: review requested

#68 Merge confl
  README.md
  wisperhub/README.md
  wisperhub/app.js
  wisperhub/index.html
  wisperhub/package.json
  wisperhub/public/vite.svg
  wisperhub/src/App.css
  wisperhub/src/App.js
  wisperhub/src/assets/images/favicon.png
  wisperhub/src/assets/images/logo.png
  wisperhub/src/assets/images/send.png
  wisperhub/src/components/MainApp.js
  wisperhub/src/components/cgu/CGU.js
  wisperhub/src/components/cgu/cgu-style.css
  wisperhub/src/components/conversation/conversation-style.css
  wisperhub/src/components/conversation/conversation.js
  wisperhub/src/components/dates/Dates.js
  wisperhub/src/components/emoji/Emoji-style.css
  wisperhub/src/components/emoji/Emoji.js
  wisperhub/src/components/loading_page/loading-page-styles.css
  wisperhub/src/components/logging/Logging.js
  wisperhub/src/components/logging/logging-style.css
  wisperhub/src/components/message/Message.js
  wisperhub/src/components/message_composer/MessageComposer.js
  wisperhub/src/components/message_composer/input_message/InputMessage.js
  wisperhub/src/components/message_composer/messageComposer-style.css
  wisperhub/src/components/registration_form/RegistrationForm.js
  wisperhub/src/components/registration_form/registration-form-style.css
  wisperhub/src/main.jsx
  wisperhub/webpack.config.js
Labels: review requested
